name: Jazzy Source Build
on:
  workflow_dispatch:
  push:
    branches:
      - jazzy
    paths:
      - '**.hpp'
      - '**.h'
      - '**.cpp'
      - '**.py'
      - '.github/workflows/jazzy-source-build.yml'
      - '**/package.xml'
      - '**/CMakeLists.txt'
      - 'beckhoff_ads_driver.jazzy.repos'
jobs:
  source:
    uses: ros-controls/ros2_control_ci/.github/workflows/reusable-ros-tooling-source-build.yml@master
    with:
      ros_distro: jazzy
      ref: jazzy
      container: ubuntu:24.04
